stages:
- test
- deploy

language: python

before_install:
- pip install poetry

install:
- poetry check
- poetry install

script:
- ./scripts/test.sh

after_success:
- poetry run codecov

jobs:
  include:
  - os: linux
    dist: xenial
    python: 3.7

  - os: linux
    dist: xenial
    python: 3.8

